import 'package:hive_ce/hive_ce.dart';

import '../../features/client/domain/models/transfer_progress.dart';
import '../../features/client/domain/models/transfer_record.dart';

part 'hive_adapters.g.dart';

/// Central Hive adapter registration for the app.
///
/// Adapters are generated by `hive_ce_generator` into `hive_adapters.g.dart`,
/// and the `registerAdapters()` extension into `hive_registrar.g.dart`.
@GenerateAdapters([
  AdapterSpec<TransferRecord>(),
  AdapterSpec<TransferDirection>(),
])
class HiveAdapters {}
