// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:file_sharing/core/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ServerSettingsAdapter());
    registerAdapter(SharedFolderAdapter());
    registerAdapter(TransferDirectionAdapter());
    registerAdapter(TransferRecordAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ServerSettingsAdapter());
    registerAdapter(SharedFolderAdapter());
    registerAdapter(TransferDirectionAdapter());
    registerAdapter(TransferRecordAdapter());
  }
}
